### ISSUE TITLE
Fix website pages #tags

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/http-apis.github.io#56]
If trying to link to a tag in the URL in the website like https://www.hydraecosystem.org/00-Home#what-makes-the-difference the result is that the title and upper part of the paragraph got hidden underneath the header.

**Comment by de-sh** [comment]
The issue is caused because of a lack of upper margin. We can fix this easily, but I think it will be better to refactor the site completely to use a better UI than it is using right now. 

I am working on something along the lines of the following, will get to it as soon as possible.

![screenshot](https://user-images.githubusercontent.com/18750864/60953724-58286e80-a31b-11e9-9c89-a5ed851a3b09.png)

**Comment by xadahiya** [comment]
Done!
